# fly.toml file generated for hv0357-portfolio-server on 2023-03-05T00:16:57+07:00

app = "hv0357-portfolio-server"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 10
    soft_limit = 8

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
